import { Upgrade } from './types.ts';

export const UPGRADES: Upgrade[] = [
  {
    id: 'resonance',
    name: 'Neural Resonance',
    description: 'Increases the output of every manual interaction.',
    baseCost: 20,
    costMultiplier: 1.17,
    type: 'click',
    power: 1,
  },
  {
    id: 'collector',
    name: 'Flux Collector',
    description: 'Automated drones that harvest ambient energy fluctuations.',
    baseCost: 150,
    costMultiplier: 1.17,
    type: 'auto',
    power: 1,
  },
  {
    id: 'harvester',
    name: 'Quantum Harvester',
    description: 'Extracts energy from sub-atomic quantum vibrations.',
    baseCost: 1500,
    costMultiplier: 1.17,
    type: 'auto',
    power: 8,
  },
  {
    id: 'refinery',
    name: 'Spectral Refinery',
    description: 'Processes raw entropy into pure, usable Aether.',
    baseCost: 18000,
    costMultiplier: 1.16,
    type: 'auto',
    power: 45,
  },
  {
    id: 'conduit',
    name: 'Primal Conduit',
    description: 'A direct uplink to the core of the universal stream.',
    baseCost: 250000,
    costMultiplier: 1.16,
    type: 'auto',
    power: 240,
  },
  {
    id: 'forge',
    name: 'Singularity Forge',
    description: 'Uses micro-black holes to generate massive power output.',
    baseCost: 3500000,
    costMultiplier: 1.15,
    type: 'auto',
    power: 1200,
  },
  {
    id: 'void_engine',
    name: 'Void Engine',
    description: 'Harnesses the energy of non-existence to power the matrix.',
    baseCost: 50000000,
    costMultiplier: 1.15,
    type: 'auto',
    power: 6500,
  },
  {
    id: 'aether_array',
    name: 'Aether Array',
    description: 'Massive structures that span across galactic clusters.',
    baseCost: 850000000,
    costMultiplier: 1.14,
    type: 'auto',
    power: 38000,
  },
  {
    id: 'chronos_core',
    name: 'Chronos Core',
    description: 'Manipulates time to generate energy from future states.',
    baseCost: 12000000000,
    costMultiplier: 1.14,
    type: 'auto',
    power: 210000,
  }
];

export const INITIAL_STATE = {
  aether: 0,
  totalAetherEarned: 0,
  clickCount: 0,
  upgrades: {
    resonance: 0,
    collector: 0,
    harvester: 0,
    refinery: 0,
    conduit: 0,
    forge: 0,
    void_engine: 0,
    aether_array: 0,
    chronos_core: 0,
  },
  lastSave: Date.now(),
};

export const SAVE_KEY = 'multiclick_game_save_v2';